#!/bin/bash

# functions ---
function message() {
	if ! [[ $2 ]]; then
		echo -e '\033[1;32m'$1'\033[0m'
	else
		echo -e '\033[1;32m'$1'\033[1;37m → \033[1;34m'$2'\033[0m'
	fi
}

function message-success() {
	if ! [[ $2 ]]; then
		echo -e '\033[1;33m'$1'\033[0m'
	else
		echo -e '\033[1;33m'$1'\033[1;37m → \033[1;35m'$2'\033[0m'
	fi
}

function addline() {
	echo -e '\033[1;36m======================================\033[0m'
}
# --- functions

message "Введите название проекта: "
read name

message "Введите описание проекта: "
read description

addline
echo -e "\n"

# package.json ---
PACKAGE_AUTHOR=$(git config --global user.email)

message "Добавление автора проекта($PACKAGE_AUTHOR)" "package.json"; npx npe author "$PACKAGE_AUTHOR" &>/dev/null
message "Добавление названия проекта" "package.json"; npx npe name "$name" &>/dev/null
message "Добавление описания проекта" "package.json"; npx npe description "$description" &>/dev/null
message "Добавление версии проекта" "package.json"; npx npe version "1.0.0" &>/dev/null
# --- package.json

# README.md ---
echo -e "# $name\n$description\n" > README.md
echo -e "## Как запустить\n" >> README.md
echo -e "**Установить зависимости**" >> README.md
echo -e "- \`npm install\`" >> README.md
echo -e "\n**Режим живого сервера**" >> README.md
echo -e "- \`npm run watch\`       - сборка и запуск live-server в режиме developer" >> README.md
echo -e "- \`npm run prodwatch\`   - сборка и запуск live-server в режиме production" >> README.md
echo -e "\n**Режим сборки**" >> README.md
echo -e "- \`npm run build\`       - сборка проекта в режиме production" >> README.md
echo -e "- \`npm run devbuild\`    - сборка проекта в режиме developer" >> README.md
echo -e "\nДокументация: https://github.com/alexsoin/gw-starter-kit" >> README.md

message "Создан файл" "README.md" 
# --- README.md

# rm & git init ---
rm ./src/assets/img/gwst.png
message "Удален файл" "./src/assets/img/gwst.png"

rm ./static/favicon.ico
message "Удален файл" "./static/favicon.ico"

rm -fr .git
message "Удален каталог" ".git"

git init
message "Инициализирован" "git init"

rm -fr init
# --- rm & git init

# complete ---
echo -e "\n"
addline
message-success "	Проект успешно проинициализирован!"
message-success "	Не забудьте при необходимости отредактировать содержимое файлов" "index.js, index.scss, variables.scss и index.twig"
addline
echo -e "\n"
# --- complete
