#!/bin/bash

# functions ---
function message() {
	if ! [[ $2 ]]; then
		echo -e '\033[1;32m'$1'\033[0m'
	else
		echo -e '\033[1;32m'$1'\033[1;37m → \033[1;34m'$2'\033[0m'
	fi
}

function message-success() {
	if ! [[ $2 ]]; then
		echo -e '\033[1;33m'$1'\033[0m'
	else
		echo -e '\033[1;33m'$1'\033[1;37m → \033[1;35m'$2'\033[0m'
	fi
}

function addline() {
	echo -e '\033[1;36m======================================\033[0m'
}
# --- functions

message "Введите название проекта: "
read name

message "Введите описание проекта: "
read description

addline
echo -e "\n"

# README.md ---
echo -e "# $name\n$description\n" > README.md
echo -e "## Как запустить\n" >> README.md
echo -e "- \`npm i\`          - установка зависимостей" >> README.md
echo -e "- \`npm run dev\`    - запуск live-server" >> README.md
echo -e "- \`npm run build\`  - сборка проекта" >> README.md
echo -e "\n---\n" >> README.md
echo -e "\nДокументация: https://github.com/alexsoin/pepelac" >> README.md

message "Создан файл" "README.md"
# --- README.md

# rm & git init ---
rm ./package-lock.json
rm ./LICENSE
rm -fr .git
git init
message "Инициализирован" "git init"

rm -fr init
# --- rm & git init

# complete ---
echo -e "\n"
addline
message-success "	Проект успешно проинициализирован!"
message-success "	Не забудьте при необходимости отредактировать содержимое файлов" "index.js, index.scss, variables.scss и index.twig"
addline
echo -e "\n"
# --- complete
